name: AutoModX
version: 2.4
author: CapitainFoxy
website: -
api-version: 1.18
database: true
load: MIDDLE
main: net.automodx.AutoModX
commands:
  automodx:
    description: Main command for AutoModX plugin
    permission: automodx.use
permissions:
  automodx.use:
    description: Allows a player to use AutoModX commands
    default: op  
